<<<<<<< HEAD
# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=9900
server.servlet.context-path=/pharmacy

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
=======
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082
>>>>>>> f464a60a925f4cdf5c40f7e3e68e62664ed8fba8
