# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=9900
server.servlet.context-path=/pharmacy

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/medicines
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


